---
apiVersion: v1
kind: Namespace
metadata:
  name: garrettdavis-dev
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: garrettdavis-dev
  namespace: garrettdavis-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      garrettdavis-dev: web
  template:
    metadata:
      labels:
        garrettdavis-dev: web
    spec:
      containers:
        - name: web
          image: 10.42.0.237:5000/garrettdavis.dev:latest
      imagePullSecrets:
        - name: registry-key
---
apiVersion: v1
kind: Service
metadata:
  name: garrettdavis-dev
  namespace: garrettdavis-dev
spec:
  type: NodePort
  selector:
    garrettdavis-dev: web
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
---
apiVersion: v1
kind: Secret
metadata:
  name: registry-key
  namespace: garrettdavis-dev
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJkb2NrZXJodWIuaW8vcHN1ZWRvIjogewoJCQkiYXV0aCI6ICJZMjlzYjNOellXdzZRVGx6WjJRbE9EUnJhVmsxIgoJCX0KCX0KfQo=
type: kubernetes.io/dockerconfigjson
